name: publish

on:
  push:
    branches:
      - test

permissions:
  contents: read
  packages: write

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the hello-docker image
        run: |
          docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:staging
          docker push ghcr.io/deselikem/hello-docker-gcr-demo:staging